Решение задач 1 модуля
js-tasks-ru/vue-20210511_forauto77 pull request #2
Opened 2021-05-23 19:47 UTC by roman162

2021-05-23 19:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-23 20:34 UTC, ShGKme requested changes
Требуется доработка 02-MarkedList и 4-MeetupPageDraft (не доделана).
Остальные задачи приняты

2021-05-23 20:34 UTC, ShGKme commented on 01-basics/02-MarkedList/index.html
> +    </li>
Лучше избегать сложной логики (и вызова функций) в шаблоне.

В этой ситуации вызов методов не создаст проблем с производительностью. Но:

1. Требуется чуть больше думать, смотря на шаблон, чтобы понять, что эти методы не имеют побочных эффектов и работают быстро. Например, если бы это приложение было больше, чем из просто списка email-ов и фильтра, то Vue бы перезапускал вычисление этого цикла при каждом ререндеринге, каждый раз заново проверяя каждую почту. Не критично, но и не оптимально.
2. Шаблон получается менее декларативным, так как уже не декларирует значение атрибута/содержимого, а вычисляет в процессе работы.

Чтобы лучше разобраться с концепцией шаблона и вычисляемых свойств предлагается избавиться от вычисления маркировки в шаблоне и сделать для этого вычисляемое свойство.

2021-05-26 18:37 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-05-28 15:45 UTC, ShGKme requested changes
В `02-MarkedList` предлагается совсем избавиться от вызова методов в шаблоне, и оставить его декларативным, а данные подготавливать в вычисляемом свойстве.

2021-05-28 15:45 UTC, ShGKme commented on 01-basics/02-MarkedList/index.html
> +    </li>
Сложная логика в шаблоне пропала, но она просто спряталась в методе.
Лучше избегать вызова методов в шаблоне. 

В этой ситуации вызов методов не создаст проблем с производительностью. Но:
1. Требуется чуть больше думать, смотря на шаблон, чтобы понять, что эти методы не имеют побочных эффектов и работают быстро. Например, если бы это приложение было больше, чем из просто списка email-ов и фильтра, то Vue бы перезапускал вычисление этого цикла при каждом ререндеринге, каждый раз заново проверяя каждую почту. Не критично, но и не оптимально.
2. Шаблон получается менее декларативным, так как уже не декларирует значение атрибута/содержимого, а вычисляет в процессе работы.

Чтобы лучше разобраться с концепцией шаблона и вычисляемых свойств предлагается избавиться от вычисления маркировки в шаблоне и сделать для этого вычисляемое свойство.

2021-06-12 09:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-12 10:57 UTC, ShGKme approved these changes
Принято 🎉

2021-06-12 10:57 UTC, ShGKme commented on 01-basics/02-MarkedList/script.js
> +    getEmails() {
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства принято называть, как свойства, а не как функции (не с глагола, без get).

2021-06-12 10:58 UTC, merged